### ISSUE TITLE
Make the raw data more git friendly

### ISSUE THREAD

**Issue by yoshimo** [maheini/FreeStyle-Libre-3-patch#1]
Diff doesn't work well for apks so it would be great to go down further in the stack
- Have branches for the different locales
- Have commits for different versions of the app
- extract the apk on the lowest levels
- decode the files to java

Also keep in mind that 
https://github.com/gui-dos/DiaBLE/ already started on the l3

**Comment by maheini** [comment]
Hey @yoshimo 
Thanks for your notes 😊

> Have branches for the different locales

That's a good idea. I initially planned to just use the english version (to focus on a single apk), but since it's not available yet (for me) I took the first one I got.

> Have commits for different versions of the app

I guess you meant different branches? I think it's gonna slow down the speed. I'd rather like to focus on one version, and after at least one is working we might be able to extend the support.

> extract the apk on the lowest levels

You're right. It's definitely some work to do and I just created this repo to give it a start. As I do not know how to properly reverse engineer apk files now, I might not be the person solving the big questions. But I'd like to contribute and support wherever possible.

> decode the files to java

Might be the next steps. I will get some larger free time an June this year, but any pull request is welcome.

> Also keep in mind that https://github.com/gui-dos/DiaBLE/ already started on the l3

Thanks for this hint. I didn't found any ongoing work on FL3, which was the main reason I started this repo. I will check out the ongoing solution and eventually link my repo to DiaBLE (So user can find it over the FreeStyle-Libre-3-patch name on github and contribute all work together)

Again, thank you for your hints and effort. 

If you like to, I'm currently developing a Image/Carb collection App for android, where you are able to store your favorite meals. It will hopefully be released at the end of May but you can already download a pre-version here [Github Repo](https://github.com/maheini/CarbPro) (It's ad free and open source)

**Comment by maheini** [comment]
I added all your additional files and content inside readme - thanks for your contribution. I will furthermore try to extract different versions of Libre 3 apk.

Additionally, I enabled the discussions tab.
