### ISSUE TITLE
Incompatible sensor error

### ISSUE THREAD

**Issue by ltomes** [maheini/FreeStyle-Libre-3-patch#34]
Attempting to use the patched apk with my sensors results in the following error:

![Screenshot_20230121_121130](https://user-images.githubusercontent.com/4184677/213881083-ca37f22e-1c0f-4459-9702-663cc8273c54.jpg)

**Comment by maheini** [comment]
Hi @ltomes
This error message is most likely because you are using a US version Libre sensor - am I right? If yes, your only option is Libre3-Juggluco setup, as [described here](https://github.com/maheini/FreeStyle-Libre-3-patch/blob/main/Juggluco-solution/juggluco-direct-instructions/en/instructions.md). In my opinion the better solution anyways....

Let me know if that fixed your problem.

**Comment by maheini** [comment]
Btw. Juggluco is currently not available in playstore. However, here's a [download](https://github.com/maheini/FreeStyle-Libre-3-patch/raw/main/Juggluco-solution/versions/latest/Juggluco.apk)

**Comment by ltomes** [comment]
> Hi @ltomes This error message is most likely because you are using a US version Libre sensor - am I right? If yes, your only option is Libre3-Juggluco setup, as [described here](https://github.com/maheini/FreeStyle-Libre-3-patch/blob/main/Juggluco-solution/juggluco-direct-instructions/en/instructions.md). In my opinion the better solution anyways....
> 
> Let me know if that fixed your problem.

That's correct, thanks for the info I am attempting that solution now.

**Comment by maheini** [comment]
Ok, glad to hear about that. Juggluco will almost certainly work and therefore I will close this issue. If  it still doesn't work, feel free to open another issue.

Have a nice weekend, regards, maheini
